name: ParallelMethods
favicon: null
layout_spectrum: 0.18080980912782252
typography_spectrum: 0.013629858149215579
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.040128615917637944
  lightness: 0.031710718059912324
  saturation: 0.40715610748156905
  rhythmicContrast: 0.8657022630795836
purpose: []
